// PDF layout for the police-script welfare-check statement. Uses
// @react-pdf/renderer primitives (Document, Page, View, Text, StyleSheet).
//
// Plain, big, factual. Same content as the HTML page at
// /cases/[id]/police-script.

import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import React from "react";

const styles = StyleSheet.create({
  page: { padding: 36, fontFamily: "Helvetica", fontSize: 11, color: "#111", lineHeight: 1.45 },
  eyebrow: { fontSize: 9, textTransform: "uppercase", letterSpacing: 1, color: "#444", marginBottom: 4 },
  h1: { fontSize: 20, fontWeight: 700, marginBottom: 4 },
  intro: { fontSize: 10, color: "#444", marginBottom: 16, borderBottom: "1pt solid #111", paddingBottom: 12 },
  sectionTitle: { fontSize: 10, fontWeight: 700, textTransform: "uppercase", letterSpacing: 1, color: "#555", marginBottom: 6, marginTop: 14 },
  row: { flexDirection: "row", paddingTop: 4, paddingBottom: 4, borderBottom: "0.5pt dashed #bbb" },
  rowLabel: { width: 130, color: "#555", fontSize: 11 },
  rowValue: { flex: 1, fontSize: 11, fontWeight: 500, color: "#111" },
  para: { fontSize: 11, color: "#111", marginTop: 2 },
  smallNote: { fontSize: 9, color: "#444", marginTop: 6 },
  footer: { marginTop: 24, paddingTop: 8, borderTop: "0.5pt solid #ccc", fontSize: 9, color: "#666" },
});

function Row({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.row} wrap={false}>
      <Text style={styles.rowLabel}>{label}</Text>
      <Text style={styles.rowValue}>{value}</Text>
    </View>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View>
      <Text style={styles.sectionTitle}>{title}</Text>
      {children}
    </View>
  );
}

type Args = {
  fullName: string;
  dob: string;
  address: string;
  phone: string;
  generatedAt: string;
  generatedBy: string;
  caseId: string;
  lastHeardFrom: string;
  sourceLine: string;
  medication: { name: string; doseMg: number; takenAt: string } | null;
  flag: { flaggedAt: string } | null;
  stressors: string[];
  emotions: string[];
  location: { lat: number; lng: number; accuracyM: number | null; takenAt: string } | null;
  nok: Array<{ relationship: string; name: string; phone: string }>;
};

function PoliceScriptDoc(args: Args) {
  const firstName = args.fullName.split(" ")[0];
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.eyebrow}>Mental health welfare check, factual statement</Text>
        <Text style={styles.h1}>For {args.fullName}</Text>
        <Text style={styles.intro}>
          Generated by the support network portal at {args.generatedAt}. Factual statement only. No subjective or clinical information is included.
        </Text>

        <Section title="Patient">
          <Row label="Full name" value={args.fullName} />
          <Row label="Date of birth" value={args.dob} />
          <Row label="Address" value={args.address} />
          <Row label="Phone" value={args.phone} />
        </Section>

        <Section title="Reason for the welfare check">
          <Text style={styles.para}>
            This is a mental health welfare check. {firstName} may have self-harmed.
          </Text>
        </Section>

        {args.medication ? (
          <Section title="Medication taken">
            <Row label="Medication" value={`${args.medication.name}, ${args.medication.doseMg} mg`} />
            <Row label="Time taken" value={args.medication.takenAt} />
          </Section>
        ) : args.flag ? (
          <Section title="Trigger">
            <Row label="Type" value="A member of the support network flagged a distressing call." />
            <Row label="When the call was flagged" value={args.flag.flaggedAt} />
          </Section>
        ) : null}

        {(args.stressors.length > 0 || args.emotions.length > 0) ? (
          <Section title="Self-reported context at the time of trigger">
            {args.stressors.length > 0 ? <Row label="Stressors noted" value={args.stressors.join(", ")} /> : null}
            {args.emotions.length > 0 ? <Row label="Emotions noted" value={args.emotions.join(", ")} /> : null}
            <Text style={styles.smallNote}>
              These are the tags {firstName} selected when logging the dose. They are self-reported context, not a clinical assessment.
            </Text>
          </Section>
        ) : null}

        <Section title="Last heard from">
          <Row label="Time" value={args.lastHeardFrom} />
          <Row label="Source" value={args.sourceLine} />
        </Section>

        <Section title="Last known location">
          {args.location ? (
            <>
              <Row label="Coordinates" value={`${args.location.lat.toFixed(5)}, ${args.location.lng.toFixed(5)}`} />
              <Row label="Captured at" value={args.location.takenAt} />
              {args.location.accuracyM != null ? (
                <Row label="Accuracy" value={`approximately ${Math.round(args.location.accuracyM)} m`} />
              ) : null}
              <Text style={styles.smallNote}>
                This is the location captured at the time noted. It may be outdated. Treat as a starting point only.
              </Text>
            </>
          ) : (
            <Text style={styles.para}>
              No location was captured. {firstName} did not share a location at the trigger event, or location permission was not granted.
            </Text>
          )}
        </Section>

        <Section title="Next of kin">
          {args.nok.length === 0 ? (
            <Text style={styles.para}>No next of kin recorded.</Text>
          ) : (
            args.nok.map((m, i) => (
              <Row key={i} label={m.relationship} value={`${m.name}, ${m.phone}`} />
            ))
          )}
        </Section>

        <Section title="What this document does not contain">
          <Text style={styles.smallNote}>
            By design, this statement excludes severity ratings, any free-text reflection {firstName} may have written, and the &quot;what is driving this&quot; or &quot;what would help&quot; prompts. Those details are kept inside the support network&apos;s portal and were considered too subjective for a police welfare-check script.
          </Text>
        </Section>

        <Text style={styles.footer} fixed>
          Generated by the Ongoing Care portal for {args.generatedBy}. Case {args.caseId}.
        </Text>
      </Page>
    </Document>
  );
}

export async function renderPoliceScriptPdf(args: Args): Promise<Buffer> {
  return await renderToBuffer(<PoliceScriptDoc {...args} />);
}
